version: '3.7'

services:
  virtualenv:
    image: atsigncompany/virtualenv:devvip
    ports:
      - '127.0.0.1:6379:6379'
      - '64:64'
      - '127.0.0.1:9001:9001'
      - '25000-25017:25000-25017'
    extra_hosts:
      - 'vip.ve.atsign.zone:127.0.0.1'
  masqdns:
    image: atsigncompany/masqdns:devvip
    ports:
      - '127.0.0.1:5380:8080'
      - '53:53/udp'
